artis3n/ansible-role-tailscale

- CODE_OF_CONDUCT.md
- README.md
- meta/main.yml
> Fix Platforms in meta/main.yml

- .github/workflows/ci.yml
- defaults/main.yml
- meta/main.yml
- molecule/default/molecule.yml
- tasks/main.yml
Resolves #15 
Resolves #7 
Resolves #9
> Adding new distros via a matrix workflow

- .github/workflows/ci.yml
- README.md
- meta/main.yml
> Adding Amazon Linux 2 and Debian Buster

- meta/main.yml
Correct version descriptions for Debian and Amazon Linux 2
> Fix Ansible Galaxy metadata

- .github/workflows/ci.yml
- meta/main.yml
> Supporting Debian 9

- .github/workflows/ci.yml
- Pipfile.lock
- handlers/main.yml
- meta/main.yml
- molecule/default/verify.yml
- tasks/arch.yml
- tasks/main.yml
> Adding Arch support

- Makefile
- tasks/main.yml
> Adding PopOS support

- .github/workflows/ci.yml
- Pipfile.lock
- defaults/main.yml
- meta/main.yml
- tasks/debian.yml
- tasks/main.yml
> Adding Debian bullseye and sid

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- README.md
- defaults/main.yml
- tasks/main.yml
Maintains contributions in #112 with some cleanup. Needs to be filed by me so the Tailscale authkey is correctly used in the CI tests. See <https://github.com/artis3n/ansible-role-tailscale#development-and-contributing>
cc @pellegrino
> Add oraclelinux

- .github/workflows/ci.yml
- molecule/default/verify.yml
- molecule/skip-authentication/verify.yml
- tasks/main.yml
Maintains contributions in #118 with some cleanup. Needs to be filed by me so the Tailscale authkey is correctly used in the CI tests. See https://github.com/artis3n/ansible-role-tailscale#development-and-contributing
cc @cmmarslender
> Update condition for tailscale status

- .github/workflows/ci.yml
- .gitignore
- .pre-commit-config.yaml
- .yamllint
- Makefile
- Pipfile
- Pipfile.lock
- molecule/default/molecule.yml
- molecule/skip-authentication/molecule.yml
- molecule/vars-priority/molecule.yml
- tasks/debian.yml
- vars/main.yml
> Resolving Debian 11 reversion with `ansible_distribution_release`

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- .github/workflows/security.yml
- .pre-commit-config.yaml
- Makefile
- Pipfile.lock
- README.md
- handlers/main.yml
- meta/main.yml
- molecule/default/cleanup.yml
- molecule/default/converge.yml
- molecule/default/verify.yml
- molecule/skip-authentication/converge.yml
- molecule/skip-authentication/verify.yml
- molecule/vars-priority/converge.yml
- molecule/vars-priority/verify.yml
- tasks/arch.yml
- tasks/centos.yml
- tasks/debian.yml
- tasks/fedora.yml
- tasks/main.yml
- chore: update syntax to use ansible FQCNs
- chore: install pre-commit hooks in codespace
Closes #61
> chore: update dependencies and move to ansible FQCNs

- .devcontainer/Dockerfile
- .github/workflows/ci.yml
- README.md
- vars/main.yml
> feat: add support for rockylinux

- .github/workflows/ci.yml
- Makefile
- meta/main.yml
> feat: add ubuntu 22.04 to ci suite

- .github/workflows/ci.yml
- Makefile
- meta/main.yml
- tasks/main.yml
> feat: add support for debian 12

- .pre-commit-config.yaml
- README.md
- poetry.lock
- docs: add openssf best practices badge
- chore: update dependencies
> Add badge for OpenSSF Best Practices

- .pre-commit-config.yaml
- poetry.lock
- chore: update ansible-lint
- chore: update pre-commit config
> chore: update deps

- .devcontainer/devcontainer.json
- .github/workflows/pull_request.yml
- .github/workflows/pull_request_target.yml
- .pre-commit-config.yaml
- Makefile
- molecule/args/molecule.yml
- molecule/default/molecule.yml
- molecule/idempotent-up/molecule.yml
- molecule/skip-authentication/molecule.yml
- molecule/state-absent/molecule.yml
- molecule/state-present/molecule.yml
- molecule/vars-priority/molecule.yml
- poetry.lock
> chore: run ansible lint pinned to production profile

- .pre-commit-config.yaml
- poetry.lock
- tasks/debian/install.yml
> fix: error in debian prelease version parsing

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_target.yml
- .pre-commit-config.yaml
https://github.com/artis3n/ansible-role-tailscale/issues/266
> fix: roll back to ubuntu 20.04 in CI suite

- .github/workflows/pull_request_target.yml
- README.md
- tasks/opensuse/install.yml
- tasks/opensuse/uninstall.yml
- tasks/uninstall.yml
> feat: add opensuse CI containers. configure uninstall tasks for opensuse

- Makefile
- molecule/args/molecule.yml
- molecule/default/molecule.yml
- molecule/idempotent-up/molecule.yml
- molecule/skip-authentication/molecule.yml
- molecule/state-absent/molecule.yml
- molecule/state-present/molecule.yml
- molecule/vars-priority/molecule.yml
- poetry.lock
- pyproject.toml
- requirements.yml
- tasks/opensuse/install.yml
- tasks/opensuse/uninstall.yml
> fix: working on implementing cgroupsv2 support for Molecule

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_target.yml
This reverts commit 06c65ea5754beaa7bc63cf8f0a6d42386e9d0431.
> Revert "test: return to ubuntu-latest with cgroupsv2 (#273)"

- molecule/args/verify.yml
- molecule/default/verify.yml
- molecule/idempotent-up/verify.yml
- molecule/skip-authentication/verify.yml
- molecule/state-absent/converge.yml
- molecule/state-present/verify.yml
- molecule/vars-priority/verify.yml
- tasks/install.yml
- tasks/uninstall.yml
> feat: cover status checks for expired auth keys

- .devcontainer/devcontainer.json
- .github/workflows/pull_request.yml
- .github/workflows/pull_request_target.yml
- .pre-commit-config.yaml
- LICENSE
- README.md
- molecule/args/cleanup.yml
- molecule/args/verify.yml
- molecule/default/cleanup.yml
- molecule/default/verify.yml
- molecule/idempotent-up/cleanup.yml
- molecule/idempotent-up/verify.yml
- molecule/skip-authentication/verify.yml
- molecule/state-absent/verify.yml
- molecule/state-present/cleanup.yml
- molecule/state-present/verify.yml
- molecule/vars-priority/cleanup.yml
- molecule/vars-priority/verify.yml
- poetry.lock
- pyproject.toml
- tasks/install.yml
- tasks/lib/up-state.yml
> Store state in XDG_STATE_HOME

- .github/workflows/pull_request_target.yml
Thanks @mcdonnnj for maintaining this image!
> chore: test with cisagov image instead of my own

- .github/workflows/pull_request_target.yml
- README.md
- meta/main.yml
- poetry.lock
- pyproject.toml
- tasks/install.yml
- tasks/uninstall.yml
- vars/main.yml
Adds support for Amazon Linux 2023 servers, which are based on Fedora.
> feat: support amazon linux 2023

- .pre-commit-config.yaml
- poetry.lock
Needed to bump pyyaml due to https://github.com/python-poetry/poetry/issues/8287
So just update everything
> chore: update dependencies

- README.md
> docs: resize readme image

- .github/workflows/pull_request_target.yml
- vars/main.yml
- **fix: use gnupg instead of gnupg2**
- **ci: replace cisagov image with geerlingguy**
Closes #441
Closes #442
> Fix gnupg and replace cisagov ci image

- .github/workflows/molecule.yml
- .github/workflows/pull_request_target.yml
- .github/workflows/release.yml
> ci: add a release workflow

- README.md
> update oauth scope needed for oauth authkey
