meta/main.yml
Amazon Linux 2 uses `versions: any` but Arch apparently needs `versions: all`. I love the standardization.
=> Fix Galaxy meta for Arch

README.md
As written previously, the line added to `/etc/sysctl.conf` is actually
```
net.ipv4.ip_forward=1=1
```
which is invalid
=> fix sysctl ip_forward example in README

molecule/default/cleanup.yml
`logout` disconnects from Tailscale and expires the machine's key, whereas `down` only disconnects from Tailscale.
=> Move cleanup from down to logout

.pre-commit-config.yaml, tasks/debian.yml
Debian 11 no longer requires python-apt (python2) and can use python3-apt like a regular distro.
Fixes #124
=> Fix Debian 11 failure with official release

Makefile, Pipfile.lock, tasks/main.yml
Due to the recent change for the CI secret, the role was not correctly checking that the `tailscale_auth_key` variable was correctly set. An empty string was passing the initial task and causing the role to hang at the "Bring Tailscale Up" step (see https://github.com/artis3n/ansible-role-tailscale/pull/132/checks?check_run_id=3463189484 ).
This fixes that so the role correctly fails immediately if the `tailscale_auth_key` is an empty string.
=> Fix authkey existence check

vars/main.yml
Getting CI to pass on #158 by bringing the fork inside the repo.
---
Change:
- Piggyback off of CentOS support and add RHEL support.
- Note that tailscale provides a repo for RHEL 8, but not RHEL 7. Thus,
we use the RHEL 8 repo if we're on RHEL 8, otherwise we default to
the CentOS one.
Signed-off-by: Rick Elrod <rick@elrod.me>
=> Add RHEL support

tasks/main.yml
Depending on the terminal/browser/os used, clicking on the link in the error message might lead you to an incorrect url (in my case, it was `https://login.tailscale.com/admin/authkeys./n`
Addind a space at the end of the error message should fix this reliably.
=> Make URL in error message clickable

tasks/main.yml
The old path redirects to this one but may as well update it.
=> fix: update authkey admin URL to new path

tasks/install.yml
Refs: https://github.com/artis3n/ansible-role-tailscale/issues/203
If `""` is added by `quote` keyword, the tailscale up command is `tailscale up "--authkey=FILTERED --advertise-exit-node=true"`. It is treated as `["tailscale", "up", "--authkey=FILTERED  --advertise-exit-node=true"]`, so the command will fail.
I remove the `quote` keyword to prevent this behavior.
=> Fix quote of tailscale args

tasks/debian/install.yml, tasks/debian/uninstall.yml, tasks/main.yml
There is already a a PR outstanding but missing a few more things.  FYI, `cache_valid_time` implies `update_cache`.
=> fix: switch debian to use cache_valid_time

requirements.yml, tasks/install.yml
We should remove the legacy state folder if it is present on the system.
Also, resolve <https://github.com/ansible/galaxy/issues/2302> by bypassing Ansible Galaxy and referencing `community.general` in CI by its git URL.
This will fix the ~60% chance of a CI test timing out to install the collection from Ansible Galaxy.
Closes #279
=> fix: remove legacy state if present and bypass ansible galaxy

.github/workflows/molecule.yml, .github/workflows/pull_request_target.yml
Really would like to avoid it, but it seems necessary.
=> fix: need to use a github environment to protect access to github secrets

.github/workflows/pull_request_target.yml
@geerlingguy made an Amazon Linux 2023 image and it updates on a schedule, so don't need to maintain my own anymore :)
=> use geerlingguy amazonlinux2023 image

vars/main.yml
> OSMC is based on Debian. Debian uses a packaging system called APT
> (Advanced Packaging Tool) to retrieve and install packages. OSMC
> includes all upstream Debian packages, [...]
Source: https://osmc.tv/wiki/general/installing-packages-via-apt/
=> feat: add OSMC to list of Debian distros

README.md
New Ansible Galaxy site changed their IDs: https://galaxy.ansible.com/api/v1/roles/.
=> fix: correct galaxy badge

README.md
shields.io updated their URLs in response to Galaxy’s new APIs.
=> docs: restore shields.io role download badge

.ansible-lint, README.md, defaults/main.yml, molecule/oauth/cleanup.yml, molecule/oauth/converge.yml, molecule/oauth/headscale.config.yaml, molecule/oauth/init_tailscale_vars.yml, molecule/oauth/molecule.yml, molecule/oauth/prepare.yml, molecule/oauth/verify.yml, tasks/install.yml
this fixes 
https://github.com/artis3n/ansible-role-tailscale/issues/398
Tailscale docs:
https://tailscale.com/kb/1215/oauth-clients/#registering-new-nodes-using-oauth-credentials
Source code reference:
https://github.com/tailscale/tailscale/blob/869b34ddeb4175df2b08cdc3d6cd9a350ec81059/cmd/tailscale/cli/up.go#L1068
=> [FEAT] add OAuth key integration and additional URL-style params to --auth-key flags (ephemeral & preauthorized)

.ansible-lint, .devcontainer/devcontainer.json, Makefile, README.md, tasks/install.yml
Fixes the devcontainer environment which broke when we moved to python 3.12 in this repo: https://github.com/artis3n/ansible-role-tailscale/actions/runs/7792353009/job/21250173006#step:4:4434 .
Fixes typo of `tailscale_authkey_sting`.
=> bump the base devcontainer image

.github/workflows/molecule.yml, .github/workflows/pull_request_target.yml, Makefile
- fix: pin headscale temporarily to 0.22
- test workflow change
Closes #432
=> Fix headscale error

.github/workflows/pull_request_target.yml
There are headscale tests run directly from this workflow file instead of the `molecule.yml` reusable workflow, add the temp env var
=> update missing headscale temp env var

handlers/main.yml, tasks/install.yml
Context: if a variable is defined within a set_fact module call, and the variable value is used within the new varibles defined via set_fact. If the variable defined already has a value, within the set_fact variables the existing value will be used instead of the newly assigned value. Encounted with Ansible version 2.16.3
Reproduction example:
```yaml
- ansible.builtin.set_fact:
status: "no a json"
- ansible.builtin.shell: >
echo "{ \"Self\": { \"Online\": true }, \"Version\": 1.0 }"
changed_when: false
register: tailscale_status
- vars:
status: "{{ tailscale_status.stdout | from_json }}" # <- does not take place
ansible.builtin.set_fact:
tailscale_is_online: "{{ status.Self.Online }}"
tailscale_version: "{{ status.Version }}"
```
---
How I encountered the issue. In a project where the …
=> fix: workaround ansible inconsistent var handling

molecule/state-absent/verify.yml, tasks/debian/uninstall.yml, tasks/uninstall.yml
Often, when I run the role with `state: absent`, the next role run with `state: present` will fail with different errors. For example, like described in the bug
https://github.com/artis3n/ansible-role-tailscale/issues/429
After talking to Tailscale support, that issue might happen if `/var/lib/tailscale/` still contains the previous machine identity (state, auth key, id, etc). 
We have to remove this folder during decommission.
Fortunately, Ubuntu package has that task inside the `tailscale.postrm`, (if the user rune `apt purge tailscale`):
```sh
$ cat /var/lib/dpkg/info/tailscale.postrm
#!/bin/sh
set -e
if [ -d /run/systemd/system ] ; then
systemctl --system daemon-reload >/dev/null || true
fi
if [ -x "/usr/bin/deb-systemd-helper" ]; then
if [ "$1" = "remove" ]; then
deb-systemd-helper …
```
=> [FIX] Improve decommission process_2

tasks/debian/uninstall.yml, tasks/uninstall.yml
As a follow-up to #435, after further thought I'm removing the `purge` behavior from Debian since the other distros don't have similar behavior. Instead, removing the entire `/var/lib/tailscale` directory ourselves, so that behavior is preserved across all distros. This better aligns with <https://tailscale.com/kb/1069/uninstall?tab=linux> for each distro's uninstall command.
=> fix: align uninstall behavior across distros

tasks/debian/install.yml
The Tailscale client auto-update feature requires the sources list file in `/etc/apt/sources.list.d/tailscale.list` otherwise it won't work.
=> Set filename to support auto update feature 

tasks/install.yml
This patch redacts the authkey from `tailscale up` stderr output based on `tailscale_authkey` directly instead of the `tskey.*` regex. The same change was already applied for the stdout logging in #328 (see https://github.com/artis3n/ansible-role-tailscale/blob/7ebbe49a0413b8912c02bd9a81aa54a02538f6f5/tasks/install.yml#L150).
=> Fix redacting the auth key when tailscale up fails

README.md, pyproject.toml, tasks/facts.yml, tasks/install.yml
This PR adds new facts about the node after this role successfully installs Tailscale on that node.
See the updated README for details.
Closes #462
=> feat: add node facts after role installation completes

tasks/install.yml
The `tailscale status --json` command is purely gathering data (doesn't change anything), so it's ok to run in check mode.
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_checkmode.html#enforcing-or-preventing-check-mode-on-tasks
From my testing, fixes #348
=> Run `tailscale status` in check mode

tasks/install.yml
tailscale_tags_string templated to `None`, which is not a valid argument.
It would template to something like `"--login-server=https://ts.example.com None --timeout=120s"`, with `None` being an invalid argument causing the following error:
```
fatal: [host]: FAILED! => {"ansible_job_id": "j1.1", "changed": true, "cmd": ["tailscale", "up", "--login-server=https://ts.example.com", "None", "--timeout=120s", "--authkey=1234"], "delta": "0:00:00.004653", "end": "2024-09-19 12:59:36.991005", "finished": 1, "msg": "non-zero return code", "rc": 1, "results_file": "/root/.ansible_async/j1.1", "start": "2024-09-19 12:59:36.986352", "started": 1, "stderr": "too many non-flag arguments: [\"None\" \"--timeout=120s\" \"--auth-key=1234\"]", "stderr_lines": ["too many non-flag arguments: [\"None\" …
```
=> Fix templating of tailscale_args_string if tailscale_tags is an empty list

.github/workflows/pull_request_target.yml, .gitignore, README.md, filter_plugins/warn.py, meta/main.yml, poetry.lock, pyproject.toml, tasks/main.yml
Add a `WARNING` at end of role execution about the new collection, https://github.com/artis3n/ansible-collection-tailscale.
The only real option to do that with ansible is the `meta` module, and the only module option prior to ansible-core 2.18 is `end_play`. But I didn't want this role forcing the end of an end user's playbook. So this PR also sets the minimum Ansible requirement for to 2.18, which is when the `end_role` option for `meta` was added. This ends the current role only.
This will be released as a major version bump, as ansible-core 2.18 is only available in `ansible` 11.x.
=> add migration message, upgrading min ansible requirement to 2.18
